export const GET_ALL_MESSAGES_START = "GET_ALL_MESSAGES_START"
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS"
export const GET_ALL_MESSAGES_ERROR = "GET_ALL_MESSAGES_ERROR"

export const GET_AUTHORS_MESSAGES_START = "GET_AUTHORS_MESSAGES_START"
export const GET_AUTHORS_MESSAGES_SUCCESS = "GET_AUTHORS_MESSAGES_SUCCESS"
export const GET_AUTHORS_MESSAGES_ERROR = "GET_AUTHORS_MESSAGES_ERROR"

export const POST_MESSAGE_START = "POST_MESSAGE_START"
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS"
export const POST_MESSAGE_ERROR = "POST_MESSAGE_ERROR"

export const DELETE_MESSAGE_START = "DELETE_MESSAGE_START"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR"

export const GET_AUTHOR_INFO_START = "GET_AUTHOR_INFO_START"
export const GET_AUTHOR_INFO_SUCCESS = "GET_AUTHOR_INFO_SUCCESS"
export const GET_AUTHOR_INFO_ERROR = "GET_AUTHOR_INFO_ERROR"
