export const GET_MESSAGES_START = "GET_MESSAGES_START"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR"

export const GET_SELECTED_AUTHOR_MESSAGES_START =
  "GET_SELECTED_AUTHOR_MESSAGES_START"
export const GET_SELECTED_AUTHOR_MESSAGES_SUCCESS =
  "GET_SELECTED_AUTHOR_MESSAGES_SUCCESS"
export const GET_SELECTED_AUTHOR_MESSAGES_ERROR =
  "GET_SELECTED_AUTHOR_MESSAGES_ERROR"

export const GET_FILTERED_AUTHOR_MESSAGES_START =
  "GET_FILTERED_AUTHOR_MESSAGES_START"
export const GET_FILTERED_AUTHOR_MESSAGES_SUCCESS =
  "GET_FILTERED_AUTHOR_MESSAGES_SUCCESS"
export const GET_FILTERED_AUTHOR_MESSAGES_ERROR =
  "GET_FILTERED_AUTHOR_MESSAGES_ERROR"

export const POST_MESSAGE_START = "POST_MESSAGE_START"
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS"
export const POST_MESSAGE_ERROR = "POST_MESSAGE_ERROR"

export const DELETE_MESSAGE_START = "DELETE_MESSAGE_START"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR"

export const GET_AUTHORS_START = "GET_AUTHORS_START"
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS"
export const GET_AUTHORS_ERROR = "GET_AUTHORS_ERROR"

export const GET_SINGLE_AUTHOR_START = "GET_SINGLE_AUTHOR_START"
export const GET_SINGLE_AUTHOR_SUCCESS = "GET_SINGLE_AUTHOR_SUCCESS"
export const GET_SINGLE_AUTHOR_ERROR = "GET_SINGLE_AUTHOR_ERROR"
